# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mmst-app CI

on:
  pull_request:
    branches: [ "main", "releases/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    defaults:
      run:
        shell: bash
        working-directory: ./mmst-app

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install modules from lockfile
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Run Prettier
      run: npm run format-check
